version: "3.3"
services:
  backend:
    command: bash -c "poetry run uvicorn main:app --reload --host 0.0.0.0"
    image: "computerprogres-api:latest"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

