version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 4s
      retries: 5

  backend:
    command: bash -c "alembic upgrade head && poetry run python initial_data.py && poetry run uvicorn main:app --reload --host 0.0.0.0"
    image: "computerprogres-api:latest"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  app-db-data:
