version: "3.3"
services:
  backend:
    command: poetry run uvicorn main:app --host 0.0.0.0
    image: "computerprogres-api:latest"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
