"""empty message

Revision ID: 05e027b357df
Revises: 4716a65607a8
Create Date: 2021-07-07 22:57:09.323265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e027b357df'
down_revision = '4716a65607a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accuracy_value', 'value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('cpu', 'frequency',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('cpu', 'tdp',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('cpu', 'gflops',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('gpu', 'tdp',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('gpu', 'gflops',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.add_column('model', sa.Column('extra_training_time', sa.Boolean(), nullable=True))
    op.alter_column('model', 'hardware_burden',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('model', 'gflops',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('model', 'multiply_adds',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('tpu', 'tdp',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('tpu', 'gflops',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tpu', 'gflops',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('tpu', 'tdp',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('model', 'multiply_adds',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('model', 'gflops',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('model', 'hardware_burden',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('model', 'extra_training_time')
    op.alter_column('gpu', 'gflops',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('gpu', 'tdp',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('cpu', 'gflops',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('cpu', 'tdp',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('cpu', 'frequency',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accuracy_value', 'value',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
