"""empty message

Revision ID: 06924a6b32a2
Revises: 653df1a5eaa7
Create Date: 2021-06-08 02:12:46.327226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06924a6b32a2'
down_revision = '653df1a5eaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
