"""empty message

Revision ID: 107317a8b10a
Revises: d621a3e350a9
Create Date: 2021-06-17 03:48:07.822618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107317a8b10a'
down_revision = 'd621a3e350a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accuracy_type', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accuracy_type', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accuracy_type', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accuracy_type', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
