"""empty message

Revision ID: 13f079276533
Revises: ec0bb5820a1f
Create Date: 2021-06-17 05:16:30.615132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f079276533'
down_revision = 'ec0bb5820a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
