"""empty message

Revision ID: 54d1ba8700a5
Revises: ec0034ef61a3
Create Date: 2021-06-15 23:08:33.330874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d1ba8700a5'
down_revision = 'ec0034ef61a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
