"""empty message

Revision ID: 653df1a5eaa7
Revises: d8c61ee873e3
Create Date: 2021-06-07 22:07:11.966010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653df1a5eaa7'
down_revision = 'd8c61ee873e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
