"""empty message

Revision ID: 6cbc43823f31
Revises: edef3369fcd5
Create Date: 2021-06-17 05:17:23.911765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbc43823f31'
down_revision = 'edef3369fcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('link', sa.String(), nullable=True))
    op.drop_column('paper', 'links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('links', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('paper', 'link')
    # ### end Alembic commands ###
