"""empty message

Revision ID: 9f876af59e81
Revises: 
Create Date: 2021-08-02 16:46:30.401791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f876af59e81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy_type',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accuracy_type_id'), 'accuracy_type', ['id'], unique=False)
    op.create_table('cpu',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number_of_cores', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(precision=3), nullable=True),
    sa.Column('fp32_per_cycle', sa.Integer(), nullable=True),
    sa.Column('transistors', sa.Integer(), nullable=True),
    sa.Column('tdp', sa.Float(precision=3), nullable=True),
    sa.Column('gflops', sa.Float(precision=3), nullable=True),
    sa.Column('die_size', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpu_id'), 'cpu', ['id'], unique=False)
    op.create_table('dataset',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_dataset_id'), 'dataset', ['id'], unique=False)
    op.create_table('gpu',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('transistors', sa.Integer(), nullable=True),
    sa.Column('tdp', sa.Float(precision=3), nullable=True),
    sa.Column('gflops', sa.Float(precision=3), nullable=True),
    sa.Column('die_size', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_id'), 'gpu', ['id'], unique=False)
    op.create_table('paper',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('code_link', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('authors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_id'), 'paper', ['id'], unique=False)
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_table('tpu',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('transistors', sa.Integer(), nullable=True),
    sa.Column('tdp', sa.Float(precision=3), nullable=True),
    sa.Column('gflops', sa.Float(precision=3), nullable=True),
    sa.Column('die_size', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpu_id'), 'tpu', ['id'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('default', 'reviewer', 'admin', 'super_admin', name='roleenum'), server_default='default', nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('submission',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'need_information', 'approved', 'declined', name='statusenum'), server_default='pending', nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.create_table('task_dataset',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_task_dataset_id'), 'task_dataset', ['id'], unique=False)
    op.create_table('message',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_table('model',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hardware_burden', sa.Float(precision=3), nullable=True),
    sa.Column('training_time', sa.BigInteger(), nullable=True),
    sa.Column('gflops', sa.Float(precision=3), nullable=True),
    sa.Column('epochs', sa.BigInteger(), nullable=True),
    sa.Column('number_of_parameters', sa.BigInteger(), nullable=True),
    sa.Column('multiply_adds', sa.Float(precision=3), nullable=True),
    sa.Column('number_of_cpus', sa.Integer(), nullable=True),
    sa.Column('number_of_gpus', sa.Integer(), nullable=True),
    sa.Column('number_of_tpus', sa.Integer(), nullable=True),
    sa.Column('task_dataset_id', sa.Integer(), nullable=True),
    sa.Column('extra_training_time', sa.Boolean(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('cpu_id', sa.Integer(), nullable=True),
    sa.Column('tpu_id', sa.Integer(), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpu.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['task_dataset_id'], ['task_dataset.id'], ),
    sa.ForeignKeyConstraint(['tpu_id'], ['tpu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_table('task_dataset_accuracy_type',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_dataset_id', sa.Integer(), nullable=True),
    sa.Column('accuracy_type_id', sa.Integer(), nullable=True),
    sa.Column('main', sa.Boolean(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accuracy_type_id'], ['accuracy_type.id'], ),
    sa.ForeignKeyConstraint(['task_dataset_id'], ['task_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dataset_accuracy_type_id'), 'task_dataset_accuracy_type', ['id'], unique=False)
    op.create_table('accuracy_value',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('accuracy_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(precision=3), nullable=True),
    sa.ForeignKeyConstraint(['accuracy_type_id'], ['accuracy_type.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accuracy_value_id'), 'accuracy_value', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accuracy_value_id'), table_name='accuracy_value')
    op.drop_table('accuracy_value')
    op.drop_index(op.f('ix_task_dataset_accuracy_type_id'), table_name='task_dataset_accuracy_type')
    op.drop_table('task_dataset_accuracy_type')
    op.drop_index(op.f('ix_model_id'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_task_dataset_id'), table_name='task_dataset')
    op.drop_table('task_dataset')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tpu_id'), table_name='tpu')
    op.drop_table('tpu')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_paper_id'), table_name='paper')
    op.drop_table('paper')
    op.drop_index(op.f('ix_gpu_id'), table_name='gpu')
    op.drop_table('gpu')
    op.drop_index(op.f('ix_dataset_id'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_cpu_id'), table_name='cpu')
    op.drop_table('cpu')
    op.drop_index(op.f('ix_accuracy_type_id'), table_name='accuracy_type')
    op.drop_table('accuracy_type')
    # ### end Alembic commands ###
