"""empty message

Revision ID: b42c07917e8c
Revises: 107317a8b10a
Create Date: 2021-06-17 03:53:01.630608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42c07917e8c'
down_revision = '107317a8b10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
