"""empty message

Revision ID: d455a3b4f261
Revises: f754a07b8805
Create Date: 2021-06-08 02:26:30.355890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd455a3b4f261'
down_revision = 'f754a07b8805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
