"""empty message

Revision ID: d621a3e350a9
Revises: 54d1ba8700a5
Create Date: 2021-06-17 03:36:06.886858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd621a3e350a9'
down_revision = '54d1ba8700a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dataset', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('paper', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('paper', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dataset', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dataset', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
