"""empty message

Revision ID: ec0034ef61a3
Revises: d455a3b4f261
Create Date: 2021-06-15 21:19:15.928782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0034ef61a3'
down_revision = 'd455a3b4f261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpu', sa.Column('die_size', sa.Integer(), nullable=True))
    op.add_column('cpu', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('gpu', sa.Column('die_size', sa.Integer(), nullable=True))
    op.add_column('gpu', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('tpu', sa.Column('die_size', sa.Integer(), nullable=True))
    op.add_column('tpu', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tpu', 'year')
    op.drop_column('tpu', 'die_size')
    op.drop_column('gpu', 'year')
    op.drop_column('gpu', 'die_size')
    op.drop_column('cpu', 'year')
    op.drop_column('cpu', 'die_size')
    # ### end Alembic commands ###
