"""empty message

Revision ID: ec0bb5820a1f
Revises: b42c07917e8c
Create Date: 2021-06-17 05:15:43.473419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0bb5820a1f'
down_revision = 'b42c07917e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
