"""empty message

Revision ID: edef3369fcd5
Revises: 13f079276533
Create Date: 2021-06-17 05:17:07.236882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edef3369fcd5'
down_revision = '13f079276533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('links', sa.String(), nullable=True))
    op.drop_column('paper', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('link', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('paper', 'links')
    # ### end Alembic commands ###
