"""empty message

Revision ID: f754a07b8805
Revises: 06924a6b32a2
Create Date: 2021-06-08 02:26:25.533078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f754a07b8805'
down_revision = '06924a6b32a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
