name: Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Check style
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Install poetry
        run: pip install poetry==1.1

      - name: Install dependencies
        run: poetry install
      
      - name: Run flake8
        run: poetry run flake8 app
